### ISSUE TITLE
请问在 Chrome 的商店叫什么名字?

### ISSUE THREAD

**Issue by chang-shuai** [Hishengs/bookmark-syncer#1]
目前只在 Edge 的扩展中心搜到并安装了, 在 Chrome 的扩展中心并没有搜到. 是名字和 Edge 的名字不一样吗?

**Comment by Hishengs** [comment]
> 

审核未通过，等我重新提交，需要一点时间

**Comment by Hishengs** [comment]
已发布：https://chrome.google.com/webstore/detail/bookmark-syncer/mgeeacninhjdldchnllhlncfjcajfpbp/related?hl=zh-CN&authuser=0
